### ISSUE TITLE
Talent Point/Title reward Config does not work

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-challenge-modes#10]
when accepting hardcore challenge using

Hardcore.Enable = 1
Hardcore.TitleRewards = "1 142, 60 169, 70 141, 80 128"
Hardcore.XPMultiplier = 1
Hardcore.TalentRewards = "10 1, 11 1, 12 1, 13 1, 14 1, 15 1, 16 1, 17 1, 18 1, 19 1, 20 1, 21 1, 22 1, 23 1, 24 1, 25 1, 26 1, 27 1, 28 1, 29 1, 30 1, 31 1, 32 1, 33 1, 34 1, 35 1, 36 1, 37 1, 38 1, 39 1, 40 1, 41 1, 42 1, 43 1, 44 1, 45 1, 46 1, 47 1, 48 1, 49 1, 50 1, 51 1, 52 1, 53 1, 54 1, 55 1, 56 1, 57 1, 58 1, 59 1, 60 1, 61 1, 62 1, 63 1, 64 1, 65 1, 66 1, 67 1, 68 1, 69 1, 70 1, 71 1, 72 1, 73 1, 74 1, 75 1, 76 1, 77 1, 78 1, 79 1, 80 1"
Hardcore.ItemRewards = ""

you have no extra talents after doing .level 80 and no title is given at level 1.

intended behaviour here would be 1 talent per level

i have the same issue with ->

SemiHardcore.Enable = 1
SemiHardcore.TitleRewards = "1 119, 80 172"
SemiHardcore.XPMultiplier = 1
SemiHardcore.TalentRewards = "10 1, 12 1, 14 1, 16 1, 18 1, 20 1, 22 1, 24 1, 26 1, 28 1, 30 1, 32 1, 34 1, 36 1, 38 1, 40 1, 42 1, 44 1, 46 1, 48 1, 50 1, 52 1, 54 1, 56 1, 58 1, 60 1, 62 1, 64 1, 66 1, 68 1, 70 1, 72 1, 74 1, 76 1, 78 1, 80 1"
SemiHardcore.ItemRewards = ""

I am using the repack from 6 days ago.

**Comment by ZhengPeiRu21** [comment]
Thank you for the report, I will investigate the issue!

**Comment by dkapte** [comment]
Can confirm it does not give an item or an extra talent point. I tried this on the latest commit (24 oct) and the initial commit of 07 oct. Both versions do not work and don't give extra talents or the item on the level. I tried this with .levelup command and by manually leveling to lvl 10, 15 and 20. Both same results, no extra talents and no item reward.

SlowXpGain.Enable = 1
SlowXpGain.TitleRewards = ""
SlowXpGain.TalentRewards = "10 1, 15 5, 20 6, 25 7"
SlowXpGain.ItemRewards = "20 24130"

**Comment by ZhengPeiRu21** [comment]
Thank you for confirm. Are titles and items also having this issue, or only talent points?

**Comment by dkapte** [comment]
Titles and items are also having this issue. Tested it with both commits (latest and first commit). Both fail to provide the talent point on the level entered in SlowXpGain.TalentRewards and the item in SlowXpGain.ItemRewards  when you reach the level

**Comment by dkapte** [comment]
Do you have any update regarding the status of the bug and do you need any additional testing?

**Comment by StraysFromPath** [comment]
Thank you Zheng your work is the most fun I've had in years.

**Comment by ZhengPeiRu21** [comment]
This should now be fixed in https://github.com/ZhengPeiRu21/mod-challenge-modes/commit/5e172aaa185664163014c889e7c85408c05d4d81. Please let me know if you see any more issues!

**Comment by StraysFromPath** [comment]
> This should now be fixed in [5e172aa](https://github.com/ZhengPeiRu21/mod-challenge-modes/commit/5e172aaa185664163014c889e7c85408c05d4d81). Please let me know if you see any more issues!

The talent point issue is fixed for new characters but can you put a check/refresh/fix attached to "reset all talent points" for existing characters?

Titles are not granted on level 1 such as if accepting Iron Man gives you "The Undying" title.
