### ISSUE TITLE
Talent points are reset offline

### ISSUE THREAD

**Issue by ddk2001** [ZhengPeiRu21/mod-challenge-modes#18]
Upgrades are set to talent points, but talent points are not saved after the character is offline.

**Comment by ddk2001** [comment]
At the same time, items are given to the level set, but items are not given when the level is reached

**Comment by ZhengPeiRu21** [comment]
Are you using the latest update of AzerothCore? There was an upstream bug causing bonus talents to be removed; the PR to fix it (https://github.com/azerothcore/azerothcore-wotlk/pull/14099) was just merged recently.

**Comment by ddk2001** [comment]
I use the latest Azerothcore， I'll try this updated one.Thanks.
