### ISSUE TITLE
Disable mode once level limit is reached

### ISSUE THREAD

**Issue by Ligthsx** [ZhengPeiRu21/mod-challenge-modes#19]
I love the module, regarding the module I have a small query, which is that when you reach level 80, the challenge mode you chose is still active.
I looked for it and I did not find where to put a level limit that when it reaches that level the mode is deactivated so that the players can be normal players.
Or where do I configure it so that when it reaches the required limit it is deactivated, thanks for sharing the module

**Comment by 28269890** [comment]
Sure, please provide an option to enable users to restore their account to a regular one after claiming rewards.

**Comment by ZhengPeiRu21** [comment]
Thank you for the suggestion. This would be a useful feature. I will add this feature in a future update.

**Comment by microbica** [comment]
This is a very good option, perhaps it is already implemented or is there a date to work on it?

**Comment by yuanf225** [comment]
Looking forward to this function, we should be able to customize how many levels we can't open these modes after.

**Comment by ZhengPeiRu21** [comment]
Implemented in https://github.com/ZhengPeiRu21/mod-challenge-modes/commit/bc701127fd801e4b79434e4b7e702b1dcd5b1cae. Please let me know if you see any issues!
