### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ElminsterCN** [ZhengPeiRu21/mod-challenge-modes#24]
After the character dies, it can be resurrected by going online again. Please fix this bug, thank you!

**Comment by ZhengPeiRu21** [comment]
Thank you for the report, I will investigate.

**Comment by Viskus** [comment]
Hi @ZhengPeiRu21 is there any update on this one? I'm only using the module for the hardcore aspect but stuck on this also :)

**Comment by ZhengPeiRu21** [comment]
This should be resolved with https://github.com/ZhengPeiRu21/mod-challenge-modes/commit/8fb291d59eb796f84c51c91b2c58060549daf060. Would you please check if it continues to have issues?

**Comment by Viskus** [comment]
I'm getting a warning when compiling @ZhengPeiRu21 it maybe nothing but worth noting for you.
`/home/soap/azerothcore/modules/mod-challenge-modes/src/ChallengeModes.cpp:24:13: warning: enumeration value 'HARDCORE_DEAD' not handled in switch [-Wswitch]
    switch (setting)
            ^~~~~~~
/home/soap/azerothcore/modules/mod-challenge-modes/src/ChallengeModes.cpp:48:13: warning: enumeration value 'HARDCORE_DEAD' not handled in switch [-Wswitch]
    switch (setting)
            ^~~~~~~
/home/soap/azerothcore/modules/mod-challenge-modes/src/ChallengeModes.cpp:72:13: warning: enumeration value 'HARDCORE_DEAD' not handled in switch [-Wswitch]
    switch (setting)
            ^~~~~~~
/home/soap/azerothcore/modules/mod-challenge-modes/src/ChallengeModes.cpp:96:13: warning: enumeration value 'HARDCORE_DEAD' not handled in switch [-Wswitch]
    switch (setting)
            ^~~~~~~
/home/soap/azerothcore/modules/mod-challenge-modes/src/ChallengeModes.cpp:120:13: warning: enumeration value 'HARDCORE_DEAD' not handled in switch [-Wswitch]
    switch (setting)`

**Comment by ZhengPeiRu21** [comment]
> I'm getting a warning when compiling

Thank you for testing. The warning wouldn't have impacted anything but I have cleaned it up in https://github.com/ZhengPeiRu21/mod-challenge-modes/commit/f2918a78219e7315ec65c9e07199170c4b27e225. Please let me know if you see any other issues.

**Comment by Viskus** [comment]
Thanks @ZhengPeiRu21 that has fixed the warning issue.
for some reason though now the idol to start a challenge mode isn't clickable, it's there in the graveyard but not able to be clicked
