### ISSUE TITLE
QuestOnlyExp Affects Hunter's Pets

### ISSUE THREAD

**Issue by cdenq** [ZhengPeiRu21/mod-challenge-modes#25]
Hunter Pets do not level up with the player when you are running a QuestOnlyExp challenge.

**Comment by ZhengPeiRu21** [comment]
Thank you for noticing and reporting this issue! This should be fixed in https://github.com/ZhengPeiRu21/mod-challenge-modes/commit/63c332fa6707c2242fba455409619806fec15ecf. Please let me know if you continue to see any problems.
