### ISSUE TITLE
problem disconnecting

### ISSUE THREAD

**Issue by Ligthsx** [ZhengPeiRu21/mod-challenge-modes#26]
Great work, maybe it would be useful as a suggestion to be able to make the mode you choose permanent with a database, when you disconnect the mode you chose is lost and you are now a normal character, but if the mode you chose were saved in the database , you could resume the progress you had when choosing your mode without losing your development when you disconnect.

**Comment by ZhengPeiRu21** [comment]
The modes you choose are permanent. This module uses Player Settings to store enabled challenges, so please ensure EnablePlayerSettings is set to 1 in your worldserver.conf.
