### ISSUE TITLE
Hardcore Disconnects after death (when trying to resurrect)

### ISSUE THREAD

**Issue by Viskus** [ZhengPeiRu21/mod-challenge-modes#27]
Hey ZhengPeiRu,

It seems the hardcore mode is now working in the respect that if you die you cannot come back to life, the only issue is that if you try to do so it will disconnect you from the server.
Is this intended? I suppose it works but maybe just not being able to click the button might be better?

Thanks in advance

**Comment by ZhengPeiRu21** [comment]
Yes, that is the intended behavior. Unfortunately the core does not have hooks required to disable to resurrection button, so this is the best solution I could come up with.
