### ISSUE TITLE
DEATH_KNIGHT ChallengeModes not visible

### ISSUE THREAD

**Issue by zxnhrdz** [ZhengPeiRu21/mod-challenge-modes#31]
![image](https://github.com/ZhengPeiRu21/mod-challenge-modes/assets/110412571/bd457f2e-8365-4f19-b5a2-701f8d1ae1f1)

DEATH_KNIGHT 

There is a problem with the judgment that causes level 55 not to show the mode It should be selected by default to be greater than 1 level.

Also, can it be after level 80. Remove the hardcore limit? Thanks!

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting the issue! The Death Knight issue should be fixed in a08ad50523932ec2f01cd64b8d4c7bb8d86530fa. Allowing challenges to be disabled upon reaching a given level has been implemented in bc701127fd801e4b79434e4b7e702b1dcd5b1cae.
