### ISSUE TITLE
Items worn under Iron Man or Item Quality levels are not removed due to character loading order

### ISSUE THREAD

**Issue by drozco** [ZhengPeiRu21/mod-challenge-modes#7]
Characters are loaded when logging on by AC calling CanEquipItem first for every item on the char and then _LoadCharacterSettings is called.  Problem is, the challenges fail to unload any items equipped by the character since the character settings have not been loaded yet.
This would require an AC core fix to change the loading order of the characters.

This is a minor issue since the character cannot ever equip any items like that in the first place, but to be aware of this issue.

**Comment by ZhengPeiRu21** [comment]
Thank you for the report - I appreciate you spend time to look into this. Because this would require a large core change to fix and doesn't have any impact, I think I will mark this as will not fix, but it is good to be aware of this issue.
