### ISSUE TITLE
Suggestion: Make Iron Man and Self-Crafted exclusive

### ISSUE THREAD

**Issue by drozco** [ZhengPeiRu21/mod-challenge-modes#8]
Since you cannot learn a profession on Iron Man it should be exclusive with Self Crafted challenge.
That is all.

**Comment by ZhengPeiRu21** [comment]
Implemented in https://github.com/ZhengPeiRu21/mod-challenge-modes/commit/19f520bb8fba2f9917e57e0f7d6d1aea1e925c2d.
